spring:
  application:
    name: checkout-service
  loadbalancer:
    client:
      name: products-service

server:
  port: 8070

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}} # ID de la instancia
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true

info:
  app:
    name: Checkout-Service
    description: Microservicios de checkout de productos
    version: 1.0.0

# Configuración de logging para Feign Client
logging:
  level:
    feign:
      client: DEBUG # Habilitar logging de Feign Client
    co.edu.unbosque.sw2.checkout_service.feighnclients: DEBUG
