server:
  port: 8383

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay
      routes:
        - id: checkout-service
          uri: lb://checkout-service
          predicates:
            - Path=/api/checkout/**

okta:
  oauth2:
    issuer: https://dev-2qk1lcy5ak3lc6s6.us.auth0.com/
    client-id: x1hhpraadic1LUC474sWhMnBgAbjZWnw
    client-secret: La62_hdDema2tMZdmRQcQjRVvieK8LTDLONWxxcwo6Dbo5D5nXs_07nyVoFPAQ7C
    audience: https://dev-2qk1lcy5ak3lc6s6.us.auth0.com/api/v2/

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true

info:
  app:
    name: gateway-service
    description: Configuracion de API
    version: 1.0.0

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

