server:
  port: 8383

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: checkout-service
          uri: lb://checkout-service
          predicates:
            - Path=/api/checkout/**
          filters:
            - AddRequestHeader=x-request-from,gateway
okta:
  oauth2:
    issuer: https://dev-2qk1lcy5ak3lc6s6.us.auth0.com/
    client-id: x1hhpraadic1LUC474sWhMnBgAbjZWnw
    client-secret: La62_hdDema2tMZdmRQcQjRVvieK8LTDLONWxxcwo6Dbo5D5nXs_07nyVoFPAQ7C
    audience: ${okta.oauth2.issuer}api/v2/
    logout-uri: https://dev-2qk1lcy5ak3lc6s6.us.auth0.com/v2/logout

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true

info:
  app:
    name: gateway-service
    description: Configuracion de API
    version: 1.0.0

# Configuración de logs en nivel DEBUG para ver la coincidencia de rutas en Spring Cloud Gateway
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
#Configuracion  auth0
