spring:
  application:
    name: products-service

  openfeign:
    oauth2:
      enabled: true
    clientRegistrationId: okta

okta:
  oauth2:
    issuer: https://dev-2qk1lcy5ak3lc6s6.us.auth0.com/
    audience: https://dev-2qk1lcy5ak3lc6s6.us.auth0.com/api/v2/

server:
  port: ${PORT:${SERVER_PORT:0}}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    metadata-map:
      weight: 20

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true

info:
  app:
    name: Products-Service
    description: Microservicios de productos
    version: 1.0.0

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-2qk1lcy5ak3lc6s6.us.auth0.com/
          jwk-set-uri: https://dev-2qk1lcy5ak3lc6s6.us.auth0.com/.well-known/jwks.json
