spring:
  application:
    name: products-service

server:
  port: ${PORT:${SERVER_PORT:0}} # Elige el primer puerto que encuentre que no esté en uso

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}} # Genera un id aleatorio basado en el puerto
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    metadata-map:
      weight: 20

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true

info:
  app:
    name: Products-Service
    description: Microservicios de productos
    version: 1.0.0
